"""
Fly.io artifact generation.

Called from config_build.generate_all() as part of the normal configure pipeline.
Writes fly.Dockerfile (flat, self-contained), fly.toml, and fly_deploy.sh
into the same generated/<stack>/ directory as the other artifacts.
"""

from __future__ import annotations

import shlex
from pathlib import Path


def collect_requirements(base, selected_mods) -> tuple[list[str], list[str], list[str]]:
    """Collect dnf/pip/npm for selected modules + 3rdparty deps + base.

    Mirrors the logic in config_build.build_base_image / generate_all so the
    flat fly Dockerfile installs the same packages as the shared base image
    plus the overlay's per-stack additions.
    """
    dnf: list[str] = list(base.base_requirements)
    pip: list[str] = []
    npm: list[str] = []

    for mod in selected_mods:
        for pkg in mod.dnf_requirements:
            if pkg not in dnf:
                dnf.append(pkg)
        for pkg in mod.pip_requirements:
            if pkg not in pip:
                pip.append(pkg)
        for pkg in mod.npm_global_requirements:
            if pkg not in npm:
                npm.append(pkg)
    return dnf, pip, npm


def flatten_overlay(overlay_path: Path, base_image: str,
                    dnf: list[str], pip: list[str], npm: list[str]) -> str:
    """Inline base-layer RUN steps into the overlay Dockerfile so Fly can build it standalone."""
    overlay_lines = overlay_path.read_text().splitlines()

    # Drop the original FROM (which points at localhost/repos-base:latest)
    body = []
    seen_from = False
    for line in overlay_lines:
        if not seen_from and line.strip().startswith("FROM "):
            seen_from = True
            continue
        body.append(line)

    flat = [f"FROM {base_image}", ""]
    flat.append(f"RUN dnf install -y {' '.join(shlex.quote(p) for p in dnf)} && dnf clean all")
    flat.append("RUN mkdir -p /etc/supervisor/conf.d /etc/supervisor/conf.d/disabled")
    if pip:
        flat.append(f"RUN python3 -m pip install --no-cache-dir {' '.join(shlex.quote(p) for p in pip)}")
    if npm:
        flat.append(f"RUN npm install -g {' '.join(shlex.quote(p) for p in npm)}")
    flat.append("")
    flat.extend(body)
    return "\n".join(flat)


def pick_internal_port(env_values: dict, publish_ports: list[str]) -> int:
    """Pick the main internal port for Fly's http_service.

    Preference: CITADEL_PORT > first published container port > first *_PORT env > 8080.
    """
    if "CITADEL_PORT" in env_values:
        try:
            return int(env_values["CITADEL_PORT"])
        except (ValueError, TypeError):
            pass

    for mapping in publish_ports:
        s = str(mapping).strip()
        container = s.split(":", 1)[1] if ":" in s else s
        try:
            return int(container)
        except (ValueError, TypeError):
            continue

    for k, v in env_values.items():
        if k.endswith("_PORT"):
            try:
                return int(v)
            except (ValueError, TypeError):
                continue

    return 8080


def write_fly_toml(path: Path, *, app: str, region: str, port: int,
                   memory: str = "1gb", cpus: int = 1) -> None:
    path.write_text(
        f"# Generated by REPOS — do not edit by hand\n"
        f"app = '{app}'\n"
        f"primary_region = '{region}'\n\n"
        f"[build]\n"
        f'  dockerfile = "fly.Dockerfile"\n\n'
        f"[http_service]\n"
        f"  internal_port = {port}\n"
        f"  force_https = true\n"
        f"  auto_stop_machines = 'stop'\n"
        f"  auto_start_machines = true\n"
        f"  min_machines_running = 0\n"
        f"  processes = ['app']\n\n"
        f"[[vm]]\n"
        f"  memory = '{memory}'\n"
        f"  cpu_kind = 'shared'\n"
        f"  cpus = {cpus}\n"
    )


def write_deploy_script(path: Path, *, stack: str, gen_dir: Path, workspace: Path) -> None:
    rel = gen_dir.relative_to(workspace)
    path.write_text(
        f"#!/usr/bin/env bash\n"
        f"# Generated by REPOS — deploy stack '{stack}' to Fly.io\n"
        f"set -euo pipefail\n\n"
        f'cd "$(dirname "$0")/../../.."  # workspace root\n\n'
        f"if ! command -v flyctl >/dev/null 2>&1; then\n"
        f'  echo "flyctl not found. Install: https://fly.io/docs/flyctl/install/"\n'
        f"  exit 1\n"
        f"fi\n\n"
        f'flyctl deploy \\\n'
        f'  --config "{rel}/fly.toml" \\\n'
        f'  --dockerfile "{rel}/fly.Dockerfile" \\\n'
        f'  "$@"\n'
    )
    path.chmod(0o755)


def generate_fly_artifacts(
    *,
    stack: str,
    base,
    selected_mods,
    overlay_path: Path,
    env_values: dict,
    publish_ports: list[str],
    gen_dir: Path,
    workspace: Path,
    region: str = "fra",
    memory: str = "1gb",
    cpus: int = 1,
) -> list[Path]:
    """Generate fly.Dockerfile, fly.toml, fly_deploy.sh. Returns list of written paths."""
    dnf, pip, npm = collect_requirements(base, selected_mods)

    fly_dockerfile = gen_dir / "fly.Dockerfile"
    fly_dockerfile.write_text(
        flatten_overlay(overlay_path, base.base_image, dnf, pip, npm)
    )

    port = pick_internal_port(env_values, publish_ports)
    fly_toml = gen_dir / "fly.toml"
    write_fly_toml(fly_toml, app=stack, region=region, port=port,
                   memory=memory, cpus=cpus)

    deploy_sh = gen_dir / "fly_deploy.sh"
    write_deploy_script(deploy_sh, stack=stack, gen_dir=gen_dir, workspace=workspace)

    return [fly_dockerfile, fly_toml, deploy_sh]
